### ISSUE TITLE
Framework Question: Multiple unique indexes

### ISSUE THREAD

**Issue by KateWilkins** [asensei/vapor-fluent-mongo#12]
Hi, I'm trying to create a compound index of two elements in the document being unique, is this possible? Not sure of what the syntax would be.. I've got a major & minor string values for the Counter object but I'm unsure how to combine them in the index statement, tried various things that don't compile.

```  static func prepare(on conn: Database.Connection) -> Future<Void> {
    print("Ran migration prepare")
    return Counter.index(on: conn).key(\.major).unique(true).create()
    //return Counter.query(on: conn).run()
  }
```

Many thanks
Kate

**Comment by KateWilkins** [comment]
Got it, please ignore:

```return Counter.index(on: conn).key(\.major).key(\.minor).unique(true).create()```

**Comment by valeriomazzeo** [comment]
That's correct, just call the key function again. 👍
